### ISSUE TITLE
Possible things to add to the website

### ISSUE THREAD

**Issue by titusfortner** [watir/watir.github.io#1]
We already have [Watir](http://watir.com) and [Watir-Webdriver](http://watirwebdriver.com) that we are looking to merge into this site. Much of that information is outdated, but not all of it.

Things we should consider adding to the site:

 1. Updated Formatting (aka make it pretty)
 2. About information (Team page? / Support Page?)
 3. Copy over old blog posts
 4. Copy over links to old podcasts
 5. History Page / Watir-Classic Page
 6. List of companies using Watir
 7. Move over all the 'advanced guides' from watirwebdriver.com

**Comment by thekiiingbob** [comment]
https://github.com/watir/watir.github.io/pull/2 is my stab at starting this.

I address the following for the most part:
* Updated formatting
* Advanced guides

It should set us up to add whatever else we need rather easily.

**Comment by titusfortner** [comment]
These tasks are either done, or being tracked on other issues
