### ISSUE TITLE
Copy over old blog posts

### ISSUE THREAD

**Issue by bret** [watir/watir.github.io#10]
Only the watir site has blog posts.

**Comment by titusfortner** [comment]
There are several tutorials for doing this with Disqus - http://www.girliemac.com/blog/2013/12/27/wordpress-to-jekyll/
Though I think we should specify that these are 'archived' blog posts.

**Comment by bret** [comment]
Actually there are no blog posts in Watir-webdriver.com.

**Comment by thekiiingbob** [comment]
https://github.com/watir/watir.github.io/pull/27 should take care of getting the blog posts onto the new site.
