### ISSUE TITLE
Copy over links to old podcasts

### ISSUE THREAD

**Issue by bret** [watir/watir.github.io#11]

**Comment by thekiiingbob** [comment]
The only podcasts that I saw was http://watirpodcast.zeljkofilipin.com/ (which appears on the watir.com sidebar), but it is not up and running anymore it seems. Even http://watirpodcast.com/ is broken (which is linked to from members on the team page).

Are there any other podcasts that I'm missing?

**Comment by zeljkofilipin** [comment]
The mp3 files are archived here: https://archive.org/details/WatirPodcast

I no longer have zeljkofilipin.com and watirpodcast.com domains.

This is the last good version at archive.org: http://web.archive.org/web/20140208010252/http://watirpodcast.com/

**Comment by bret** [comment]
I found this still up, but the links to the podcasts are broken. http://testingpodcast.com/category/watir-podcast/

@zeljkofilipin Is this something that can be fixed?

**Comment by zeljkofilipin** [comment]
Michael Ensminger (mensming@ieee.org) is in charge of that site.

**Comment by titusfortner** [comment]
I think that MVP should be adding "[Watir Podcast Archives](https://archive.org/details/WatirPodcast)" to the community page. 

At some point, we could download the archive page with [Wayback Machine Downloader](https://github.com/hartator/wayback-machine-downloader) and host it as a separate page/folder on this site, but I think that would be a separate issue if we wanted to go that route.

**Comment by titusfortner** [comment]
I think this is good enough for MVP: c9565bfc813c987783dc6022119f180906edd019
I created #29 to track the rest.
