### ISSUE TITLE
Guide for Installing Watir

### ISSUE THREAD

**Issue by monkifoto** [watir/watir.github.io#124]
I opended the Ruby Command Line and copy and pasted this : gem install watir
This is the error i got.

ERROR:  Could not find a valid gem 'watir' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/specs.4.8.gz)

**Comment by titusfortner** [comment]
You will get this error if you are behind a firewall or if you have certain types of anti-virus and can not access the SSL version of rubygems.

This should allow you to install watir: `gem sources -a http://rubygems.org`

But it would be worth figuring out why your system is having a problem with https.
