### ISSUE TITLE
Add Headless Section to Firefox Guide

### ISSUE THREAD

**Issue by raybaxter** [watir/watir.github.io#141]
On this page http://watir.com/guides/headless/ the link purporting to be "Headless on Chrome" references http://watir.com/guides/firefox/#headless

On the same page, the link purporting to be "Headless on Firefox" has the same href, but there is no anchor on that page #headless.  Headless is not mentioned at all.

**Comment by lucienbill** [comment]
The "Chrome" issue has been fixed.
The issue "no #headless anchor in the page http://watir.com/guides/firefox/" remains.
