### ISSUE TITLE
Enable Google Analytics

### ISSUE THREAD

**Issue by bret** [watir/watir.github.io#15]
We want to have a way of tracking which pages are getting the most traffic. This is needed for parity with wordpress.com.

Here is one tutorial on how to do this: http://joshualande.com/jekyll-github-pages-poole/

**Comment by titusfortner** [comment]
Should be plug & play here: https://github.com/watir/watir.github.io#step-2-customize-and-view-your-site

**Comment by bret** [comment]
I have no idea what you are trying to say. I see nothing about Analytics on this page.

**Comment by titusfortner** [comment]
Bad copy/paste, I meant: https://github.com/watir/watir.github.io/blob/master/_config.yml#L42

**Comment by titusfortner** [comment]
Merged - 6167b72987c943c6b4a371d19c48ab42717bde47
