### ISSUE TITLE
browser.close

### ISSUE THREAD

**Issue by PrabhaharanOII** [watir/watir.github.io#159]
On Win 10, opened a tab from main window. Using browser.last.window.close to close the newly opened tab crashes IE.

Faulting application name: IEXPLORE.EXE, version: 11.0.17134.1, time stamp: 0x6639744d
Faulting module name: ntdll.dll, version: 10.0.17134.556, time stamp: 0x319e0a75
Exception code: 0xc0000374
Fault offset: 0x000d8529
Faulting process id: 0x1d28
Faulting application start time: 0x01d500e919b03d73
Faulting application path: C:\Program Files (x86)\Internet Explorer\IEXPLORE.EXE
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 2b619a03-07f0-4d85-9cab-606243bbe5ee
Faulting package full name: 
Faulting package-relative application ID:

**Comment by titusfortner** [comment]
I'm assuming you mean `browser.windows.last.close`, and this is not unexpected for Internet Explorer. IE stores window handles in alphabetical not time-stamped order in the `browser.windows` array. Please specify by title or url which window you want to close. Watir will have additional ways of addressing this in an upcoming release.

Also, this tracker is for our website, not for our code. In the future you can raise your code related issues here: https://github.com/watir/watir/issues/
