### ISSUE TITLE
add guides locating  form elements inside a IFrame and get links or click ?

### ISSUE THREAD

**Issue by lsq** [watir/watir.github.io#164]
how to locate  form elements inside a IFrame and get links or click ?

**Comment by jkotests** [comment]
@lsq , there are guides for:
* Locating elements in frames or iframes - http://watir.com/guides/frames/
* Locating elements in general - http://watir.com/guides/locating/

Is there something specific about form fields and links in frames you think should be addressed?

**Comment by lsq** [comment]
Thanks
