### ISSUE TITLE
Add commenting

### ISSUE THREAD

**Issue by bret** [watir/watir.github.io#4]
It seems like Disqus is the right tool for comments these days and there are tutorials out there for how to integrate with Jekyll. Ideally we would port over the old comments from the wordpress sites to attach to the blog posts that re ported over.

**Comment by onweru** [comment]
> **but I hate the idea of signing on to 3rd party that would essentially control the content.** 

If this an issue, would you consider this https://staticman.net/. I have implemented it on a couple of sites. The docs are pretty decent and I found a [great tutorial](https://mademistakes.com/articles/improving-jekyll-static-comments/)

**Comment by titusfortner** [comment]
I'm calling this good for now with #126
