### ISSUE TITLE
Redirect Old Sites

### ISSUE THREAD

**Issue by titusfortner** [watir/watir.github.io#45]
Theoretically (I'm not sure how implementing these will work) there are two options for [url redirection](https://en.wikipedia.org/wiki/URL_redirection)
1. Redirect the entire domain, usually done through the domain registrar, which may or may not be WordPress.  it will try to map `http://watir.com/x/y/z.html` to `http://watir.github.io/x/y/z.html` so almost all of the links to watir.com will hit a 404 page on watir.github.io. Which is why #44 
2. Redirect each page individually: This would be a pain, but theoretically we could update each and every page from the old site to the right page on the new site: 
   `<meta http-equiv="refresh" content="0; URL='http://new-website.com'" />`
   I have no idea if/how easily we can do this on wordpress sites, but it would theoretically be kinder to everyone who has ever linked to one of our pages.

**Comment by thekiiingbob** [comment]
I vote for #1. If we add/remove/combine pages on the new site then the links will break again anyways.

**Comment by titusfortner** [comment]
We got this one figured out.
