### ISSUE TITLE
Recommended Gem

### ISSUE THREAD

**Issue by titusfortner** [watir/watir.github.io#49]
Someone just asked in Slack what gem they should be using because they have 4 currently installed (watir-webdriver, watir, watircommon & watir-classic). 

I think a link on the main page of what the current recommended gem to use would be good. We can keep that updated when we do new releases.

Especially before we release 6.0 it is a little confusing still.

**Comment by jarmo** [comment]
As far as I'm concerned then the gem everyone should have listed in their Gemfile should be always `watir` and nothing else. Everything else comes as a dependency when needed.

And by looking at the version 6.0, this seems to still be the case except there will be less watir-related dependencies.

In short, if anyone asks which gem should they have listed as a dependency, the correct answer would be watir. Or are there any reasons why this would not be true?

**Comment by titusfortner** [comment]
That's probably the right answer. Hopefully we don't have many issues with Windows / IE users before 6.0 is released. This issue was raised specifically because a new user yesterday expressed confusion and frustration.

Really, we need to get a basic up and running tutorial that we can immediately point to and that would solve this issue.

Maybe we also need to have some way to disambiguate watir / watir-webdriver / watir-classic / watircommon? Part of me thinks that we should not confuse people by asking they read it, and part of me thinks that many of them are already confused...

**Comment by titusfortner** [comment]
This is obvious in a post-v6 world.
