### ISSUE TITLE
Updated Formatting (aka make it pretty)

### ISSUE THREAD

**Issue by bret** [watir/watir.github.io#7]

**Comment by titusfortner** [comment]
The example code I think should be on the main page:
```Ruby
browser = Watir::Browser.new

browser.goto 'google.com'

browser.text_field(title: 'Search').set 'Ruby'

browser.link(text: 'Ruby Programming Language').exists?
#  => true
```

**Comment by titusfortner** [comment]
To update this issue... @thekiiingbob and I were both making stabs at this but have mostly run out of steam. The general idea is to get the site to look more like: https://www.ruby-lang.org/en/

There should be a better list for it, but for starters I'm seeing:
1. Width of content larger...
2. Top Navigation Bar is dynamic for mobile view
3. Sidebar content on each page

**Comment by titusfortner** [comment]
we have more work to do, but I'm effectively happy with what we have now as far as MVP goes. Anyone else have input?

**Comment by titusfortner** [comment]
I'm calling this one good enough for MVP. More prettiness likely to follow.
