### ISSUE TITLE
Broken link to Chrome switches in _docs/chrome.md

### ISSUE THREAD

**Issue by pwolanin** [watir/watir.github.io#78]
In master/_docs/chrome.md this link is a 404

```
See the full list of switches [here](http://src.chromium.org/svn/trunk/src/chrome/common/pref_names.cc)
```

working link seems to be
https://src.chromium.org/viewvc/chrome/trunk/src/chrome/common/pref_names.cc

**Comment by thekiiingbob** [comment]
Thanks for the heads up! Fixed it in https://github.com/watir/watir.github.io/pull/79.
