### ISSUE TITLE
Can't confirm Javascript alerts on IE 11, instead watir dismisses

### ISSUE THREAD

**Issue by vgm106** [watir/watir.github.io#86]
OS: Win 7 Enterprise 64bit
IE 11.0.9600.18617
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
watir 6.2.0
IEDriverServer 3.3.0  32bit

`browser.alert.exists?` would dismiss the alert rather than not. It does return true for the first call though. Any attempt to handle alert will close it. This means ok or confirm cannot be clicked.

**Comment by titusfortner** [comment]
Firstly, this issue tracker is for the website. Watir related bugs should be reported here: https://github.com/watir/watir/issues/new

That being said, update to Watir 6.2.1, there was a bug in 6.2.0 that could cause this issue.
